print(" ------------------------------------------------")
print("|                                                |")
print("|    01HelloWorld                                |")
print("|    Name : Annabelle Zhang                      |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print('Hello World')
