print(" ------------------------------------------------")
print("|                                                |")
print("|    08StringLoop                                |")
print("|    Name : Annabelle Zhang                      |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
answer = input("What is your string? ")
for i in answer:
        print(i)